const startPageData = [
  {
    image: "/image-1.jpg",
    bgColor: "#eaeaea",
    boxColor: "#f7f7f7",
    focusColor: 'black',
    borderColor: "#6a7282",
    // textColor: "#aaaaaa",
    siteTextColor: 'black',
    headingStrokeColor: '#000000',
  },
  {
    image: "/image-2.jpg",
    bgColor: "#7cbfda",
    boxColor: "#5a9ab1",
    borderColor: "#6CD0FB",
    focusColor: 'pink',
    headingColor: "#6CD0FB",
    // textColor: '#ffffff',
    siteTextColor: 'white',
    headingStrokeColor: '#ffffff',
  },
  {
    image: "/image-3.jpg",
    bgColor: "#f1c3ae",
    boxColor: "#f29073",
    borderColor: "#f7ecde",
    focusColor: 'pink',
    headingColor: "#341b2e",
    // textColor: 'white',
    siteTextColor: '#f7ecde',
    headingStrokeColor: '#ffffff',
  },
  {
    image: "/image-4.jpg",
    bgColor: "#1b3467",
    boxColor: "#112856",
    borderColor: "#6682b9",
    focusColor: 'pink',
    headingColor: "#6682b9",
    // textColor: '#ffffff',
    siteTextColor: '#cbd5e7',
    headingStrokeColor: '#ffffff',
  },
  {
    image: "/image-5.jpg",
    bgColor: "#df8428",
    boxColor: "#b96b1e",
    borderColor: "#fb932c",
    focusColor: 'pink',
    headingColor: "#6CD0FB",
    // textColor: '#ffffff',
    siteTextColor: 'white',
    headingStrokeColor: '#ffffff',
  },
  {
    image: "/image-6.jpg",
    bgColor: "#e6fe98",
    boxColor: "#bbc569",
    borderColor: "#e6fe98",
    focusColor: 'pink',
    headingColor: "#395b6a",
    // textColor: '#ffffff',
    siteTextColor: '#edf5d4',
    headingStrokeColor: '#ffffff',
  },
  {
    image: "/image-7.jpg",
    bgColor: "#ffa058",
    boxColor: "#ca7e42",
    borderColor: "#ffa058",
    focusColor: 'pink',
    headingColor: "#2a261d",
    // textColor: '#ffffff',
    siteTextColor: 'white',
    headingStrokeColor: '#ffffff',
  },
];

export default startPageData;