const startPageData = [
  {
    image: "/image-1.jpg",
    bgColor: "#e32541",
    boxColor: "#af0620",
    borderColor: "#ff9774",
    focusColor: 'black',
    headingColor: "#ff9774",
    siteTextColor: '#e6a5af',
    headingStrokeColor: '#e6a5af',
  },
  {
    image: "/image-2.jpg",
    bgColor: "#7cbfda",
    boxColor: "#5a9ab1",
    borderColor: "#6CD0FB",
    focusColor: 'pink',
    headingColor: "#6CD0FB",
    siteTextColor: 'white',
    headingStrokeColor: '#ffffff',
  },
  {
    image: "/image-3.jpg",
    bgColor: "#f1c3ae",
    boxColor: "#f29073",
    borderColor: "#f7ecde",
    focusColor: 'pink',
    headingColor: "#341b2e",
    siteTextColor: '#f7ecde',
    headingStrokeColor: '#ffffff',
  },
  {
    image: "/image-4.jpg",
    bgColor: "#1b3467",
    boxColor: "#112856",
    borderColor: "#6682b9",
    focusColor: 'pink',
    headingColor: "#6682b9",
    siteTextColor: '#cbd5e7',
    headingStrokeColor: '#ffffff',
  },
  {
    image: "/image-5.jpg",
    bgColor: "#df8428",
    boxColor: "#b96b1e",
    borderColor: "#fb932c",
    focusColor: 'pink',
    headingColor: "#6CD0FB",
    siteTextColor: 'white',
    headingStrokeColor: '#ffffff',
  },
  {
    image: "/image-6.jpg",
    bgColor: "#e6fe98",
    boxColor: "#bbc569",
    borderColor: "#e6fe98",
    focusColor: 'pink',
    headingColor: "#395b6a",
    siteTextColor: '#edf5d4',
    headingStrokeColor: '#ffffff',
  },
  {
    image: "/image-7.jpg",
    bgColor: "#ffa058",
    boxColor: "#ca7e42",
    borderColor: "#ffa058",
    focusColor: 'pink',
    headingColor: "#2a261d",
    siteTextColor: 'white',
    headingStrokeColor: '#ffffff',
  },
  {
    image: "/image-8.jpg",
    bgColor: "#ff4923",
    boxColor: "#ca3518",
    borderColor: "#ffa058",
    focusColor: 'pink',
    headingColor: "#3b1200",
    siteTextColor: '#edc4a5',
    headingStrokeColor: '#ffffff',
  },
  {
    image: "/image-9.jpg",
    bgColor: "#c1c1c1",
    boxColor: "#656565",
    borderColor: "#e4e4e4",
    focusColor: 'pink',
    headingColor: "#000000",
    siteTextColor: '#e0dcdc',
    headingStrokeColor: '#ffffff',
  },
];

export default startPageData;